### ISSUE TITLE
Could you add index paramter in itemBuilder?

### ISSUE THREAD

**Issue by raindy29** [tomwyr/drag-list#10]
Thanks

**Comment by tomwyr** [comment]
If dragged item index doesn't change until it is dropped, what index would expect to receive in the builder function? The actual position of an item in your list or, let's say, currently visible position of this item while it's being dragged?

**Comment by raindy29** [comment]
I want to get the position of the item in the list.
I have seen the source code, try to add itemIndex in _buildDragItem()
But feedbackItemBuilder can't understand how to get index.

**Comment by tomwyr** [comment]
I'll try to figure it out.

**Comment by tomwyr** [comment]
I wrapped *item* param in [DragItem](https://github.com/tomwyr/drag-list/commit/375c0a7cfdac64b1807c9ec1474b7f24008cb321#diff-edc68eb39fbf1906670fa6190185cbeaR20) class. You can use it to obtain index of each item, both in the items list (*itemIndex*) and currently visible position (*dispIndex*).

**Comment by raindy29** [comment]
Awesome, thanks
