### ISSUE TITLE
background color is not normal in some color 

### ISSUE THREAD

**Issue by raindy29** [tomwyr/drag-list#13]
Colors.white70 Incorrect 
Could you add a background color property?

Scaffold(
        backgroundColor: Colors.deepOrange,

            itemBuilder: (_, item, handle) => Container(
              color:Colors.white70,
              height: _itemHeight,
              child: Padding(
                padding: EdgeInsets.all(8.0),
                child:
                Container(
                  color:Colors.grey[500],
                  child:Row(children: [
                  Expanded(child: Center(child: Text(item))),
                  handle,
                ]),
                ),
              ),
            )

![圖片](https://user-images.githubusercontent.com/10285124/80552666-f1835700-89f9-11ea-9036-574b76bc9b9e.png)

**Comment by tomwyr** [comment]
Could you explain a bit more what should be the expected behavior here?
Item containers have 70% white background so it's like a mix of white and any widget background rendered underneath them.

**Comment by raindy29** [comment]
I hope white70 is my background color.
I tried to add a Container to the DragList and still couldn't achieve it.

**Comment by tomwyr** [comment]
This is how white70  will look like if there's orange color below. I guess you probably want to use a color without alpha channel in such case.

**Comment by raindy29** [comment]
Yes, I want to show the native color of white70

**Comment by tomwyr** [comment]
You need to use a color with full opacity to achieve what you want. Probably something like `Color(0xffdadada)`.
