### ISSUE TITLE
can you make it like we can drag between multiple lists

### ISSUE THREAD

**Issue by mehtahardikr** [tomwyr/drag-list#15]
can you make it like we can drag between multiple lists. conside 2 or more lists  if drag item from one list to another then it will work like same for single list right now.

**Comment by tomwyr** [comment]
I haven't planned such a feature until this is something highly requested. I believe you could try to implement it though by using [Draggable](https://www.youtube.com/watch?v=QzA4c4QHZCY) widget and move items between lists when draggable item is moved over another list which is also a drag target.

**Comment by mehtahardikr** [comment]
@tomwyr : i tried but stuck in between like i can't drag listitem to another list item by  hovering on it. it only moves when there is space between 2 items. And i also need toscroll list if user drag another listitem or same list item.
Here is example of what i have implemented yet. if you can help me then it would be great. as you have done without draggable so. just refer this video : https://drive.google.com/file/d/1lQ0HdyXqTONdFAegV5m62pzqv0FIj5Jx/view?usp=sharing
