### ISSUE TITLE
This is great but I have a a suggestion

### ISSUE THREAD

**Issue by Frank0945** [tomwyr/drag-list#2]
I recommend placing a content that is not included in the draggable

It looks like ''ListView.separated"

**Comment by RizanPSTU** [comment]
There should be an option for auto-scroll.

**Comment by tomwyr** [comment]
How should non-draggable item behave when list items get reordered?
E.g. separator could be a material widget with some elevation. Translating position of an item that changes its index would result in "falsely" rendering it above that separator.
