### ISSUE TITLE
Any chance to be able to expose the scroll controller?

### ISSUE THREAD

**Issue by YourFavouriteOreo** [tomwyr/drag-list#3]
Hey, my dude, Amazing package and solved a problem I was having. Would it be possible to have the scroll controller exposed? I just figured if we are adding content to the list in state and it updates, it doesn't scroll downwards (cause why would it ). It would be awesome to make it scroll to the bottom to show the updated content.

**Comment by tomwyr** [comment]
Hi there, glad you like it.
I updated the package to version 1.0.2 which exposes scroll controller property. Let me know if it resolves your issue with the list. 🙂

**Comment by YourFavouriteOreo** [comment]
Totally did <3 Thank you !
