### ISSUE TITLE
Extra padding or margin in Drag List?

### ISSUE THREAD

**Issue by YourFavouriteOreo** [tomwyr/drag-list#4]
Hey Tom, it seems like there is some extra padding or margin on the very top of the drag list, is it possible to make it optional or is it necessary to function?

Non-Debug View:
https://imgur.com/a/mzR3mLx

Debug View:
https://imgur.com/a/dJV3Tco

**Comment by tomwyr** [comment]
This is definitely not a desired behavior, I'll take a look at it.

**Comment by tomwyr** [comment]
Hey @YourFavouriteOreo , could you share with some code needed to reproduce this issue? When I run some basic example (i.e. DragList with Text widgets as items) there's no such problem at all.

**Comment by YourFavouriteOreo** [comment]
Hmm, I will try providing a repo with the bare minimum to re-create it
tomorrow. Currently away from my device. I'll also try re-investigating my
code. Maybe I am the buggy one.

**Comment by YourFavouriteOreo** [comment]
So I tried re-creating the problem, I copied my code to the dot on a brand new flutter project and it somehow works properly on the new project but... not on the old one ? huh?

**Comment by YourFavouriteOreo** [comment]
Found this via devtools:

https://imgur.com/a/IBctPRr

**Comment by YourFavouriteOreo** [comment]
Found the problem:
Flutter seems to calculate effective padding in their Slivers and it can sometimes be greater in certain situations when the widget tree is bigger. By default, ListView will automatically pad the list's scrollable extremities to avoid partial obstructions indicated by MediaQuery's padding.

It is overridable if you provide the ListView with a padding of 0 so the listview padding just needs to exposed. I tested it and if i use list view, the same problem presents itself and disables when overriding the padding. 

List View Documentation: 
https://api.flutter.dev/flutter/widgets/ListView-class.html

**Comment by tomwyr** [comment]
Dude, this is awesome. Thanks for pointing out the problem, I was confused for a moment why this happens. It can't wrap my head around however what is the reason that there's a padding in your scenario.

**Comment by YourFavouriteOreo** [comment]
Yeah, the debug view really confused me cause I really couldn't see where this padding was coming from. Feel free to close the issue and let me know when you expose the padding. <3

**Comment by YourFavouriteOreo** [comment]
I see you! you amazing human! I will wait for the pub update with great anticipation.

https://imgur.com/a/zSmKHjF

**Comment by tomwyr** [comment]
I updated the package to version 1.0.3.
Thanks for reporting this!
