### ISSUE TITLE
Make itemExtent optional

### ISSUE THREAD

**Issue by CiriousJoker** [tomwyr/drag-list#5]
Setting an item extent is problematic if I have child widgets that expand if I add content.

**Comment by erparker** [comment]
I'm interested in this as well! Love the widget, for now I'm having to fork and make itemExtent optional so I can have cells of differing sizes.

**Comment by yasinarik** [comment]
I can't agree more with that! I am trying to build a table widget where columns can be reordered. In my case, **I can resize the width** of each column separately. So itemExtent is really a blocker.

**Comment by tomwyr** [comment]
I see this is something you guys would really like to see added and imo usability of the widget would increase significantly. I'll try to work on this feature when I have a bit more time, however, it will probably require a lot of changes in the code to make it work.
