### ISSUE TITLE
Scroll when dragging beyond borders

### ISSUE THREAD

**Issue by 12people** [tomwyr/drag-list#8]
If a list is longer than the page, dragging an item beyond the bounds of the list widget does not scroll the list. That makes it impossible to drag an item from the top to the bottom in one drag.

It'd be nice if dragging beyond the bounds of a widget scrolled the widget automatically.

P.S. Thank you so much for making this widget — it's exactly what I need!

**Comment by tomwyr** [comment]
Added in version 1.0.6.

**Comment by 12people** [comment]
Awesome, thanks a ton!
