### ISSUE TITLE
Control Over the Custom Feedback Widget (While Dragging)

### ISSUE THREAD

**Issue by yasinarik** [tomwyr/drag-list#9]
This package is working quite well! Better than the official solution IMO.

Can you please make using a custom feedback widget (the widget while dragging) available?

I want it to become a different widget while dragging.

**Comment by tomwyr** [comment]
This should not take a lot of effort. I'll try to find some time to implement it, I'm short on time with other things though and I cannot promise anything.

**Comment by tomwyr** [comment]
I added `feedbackHandleBuilder` and `feedbackItemBuilder` to control build process of currently dragged widget. E.g. you can animate handle when an item is being raised/dropped like this:

```Dart
handleBuilder: (_) => AnimatedIcon(
  icon: AnimatedIcons.menu_arrow,
  progress: AlwaysStoppedAnimation(0.0),
),
feedbackHandleBuilder: (_, transition) => AnimatedIcon(
  icon: AnimatedIcons.menu_arrow,
  progress: transition,
),
```

I also decided to rename some properties of the widget to make the naming more coherent so it's possible that **after updating the package you will see an error** or two.
